/**
 * PostgreSQL-backed Shopify session storage.
 *
 * Replaces the default in-memory/SQLite session storage generated by the
 * Shopify CLI with a persistent PostgreSQL implementation that:
 * - Encrypts the access_token at rest using pgcrypto
 * - Stores sessions in the `merchants` table
 * - Works correctly across container restarts and multiple workers
 *
 * Usage in shopify.server.ts:
 *   import { DbSessionStorage } from "~/lib/db-session-storage.server";
 *   ...
 *   sessionStorage: new DbSessionStorage(pool),
 */

import type { Session, SessionStorage } from "@shopify/shopify-app-remix/server";
import type { Pool } from "pg";

export class DbSessionStorage implements SessionStorage {
  constructor(private readonly pool: Pool) {}

  async storeSession(session: Session): Promise<boolean> {
    const client = await this.pool.connect();
    try {
      // Upsert merchant with encrypted access_token
      await client.query(
        `
        INSERT INTO merchants
          (shopify_domain, access_token, scopes, email, installed_at)
        VALUES
          ($1, pgp_sym_encrypt($2, $3), $4, $5, NOW())
        ON CONFLICT (shopify_domain)
        DO UPDATE SET
          access_token   = pgp_sym_encrypt($2, $3),
          scopes         = $4,
          updated_at     = NOW(),
          uninstalled_at = NULL
        `,
        [
          session.shop,
          session.accessToken ?? "",
          process.env.DB_ENCRYPTION_KEY ?? "",
          session.scope ?? "",
          session.onlineAccessInfo?.associated_user?.email ?? null,
        ]
      );
      return true;
    } finally {
      client.release();
    }
  }

  async loadSession(id: string): Promise<Session | undefined> {
    // id is the Shopify session ID (typically "{shop}_offline" for offline tokens)
    const shop = id.replace("_offline", "").replace(/_online_\d+$/, "");
    const client = await this.pool.connect();
    try {
      const result = await client.query<{
        shopify_domain: string;
        access_token: string;
        scopes: string;
      }>(
        `
        SELECT shopify_domain,
               pgp_sym_decrypt(access_token, $1)::text AS access_token,
               scopes
        FROM merchants
        WHERE shopify_domain = $2
          AND uninstalled_at IS NULL
        LIMIT 1
        `,
        [process.env.DB_ENCRYPTION_KEY ?? "", shop]
      );

      if (result.rows.length === 0) return undefined;

      const row = result.rows[0];
      return {
        id,
        shop: row.shopify_domain,
        state: "",
        isOnline: false,
        accessToken: row.access_token,
        scope: row.scopes,
      } as unknown as Session;
    } finally {
      client.release();
    }
  }

  async deleteSession(id: string): Promise<boolean> {
    const shop = id.replace("_offline", "").replace(/_online_\d+$/, "");
    const client = await this.pool.connect();
    try {
      // Soft-delete: mark as uninstalled rather than hard-deleting
      await client.query(
        `UPDATE merchants SET uninstalled_at = NOW(), updated_at = NOW() WHERE shopify_domain = $1`,
        [shop]
      );
      return true;
    } finally {
      client.release();
    }
  }

  async deleteSessions(ids: string[]): Promise<boolean> {
    for (const id of ids) {
      await this.deleteSession(id);
    }
    return true;
  }

  async findSessionsByShop(shop: string): Promise<Session[]> {
    const session = await this.loadSession(`${shop}_offline`);
    return session ? [session] : [];
  }
}
