/**
 * Shopify Webhook Dispatch Router
 *
 * Replaces the stub generated by the Shopify CLI.
 *
 * All incoming Shopify webhooks arrive at this route. The handler:
 * 1. Verifies the HMAC signature — rejects any unverified request
 * 2. Resolves the merchant_id from the shop domain
 * 3. Enqueues the appropriate Celery task for background processing
 * 4. Returns HTTP 200 immediately (Shopify requires a response within 5 seconds)
 *
 * SECURITY: Uses timing-safe comparison to prevent HMAC timing attacks.
 */

import { createHmac, timingSafeEqual } from "crypto";
import type { ActionFunctionArgs } from "@remix-run/node";
import { db } from "~/lib/db.server";
import { enqueueWebhookTask } from "~/lib/queue.server";

export const action = async ({ request }: ActionFunctionArgs) => {
  // -------------------------------------------------------------------------
  // 1. Extract headers
  // -------------------------------------------------------------------------
  const hmacHeader = request.headers.get("X-Shopify-Hmac-Sha256");
  const topic = request.headers.get("X-Shopify-Topic");
  const shopDomain = request.headers.get("X-Shopify-Shop-Domain");

  if (!hmacHeader || !topic || !shopDomain) {
    return new Response("Missing required webhook headers", { status: 400 });
  }

  // -------------------------------------------------------------------------
  // 2. Read raw body (must be read before any parsing)
  // -------------------------------------------------------------------------
  const rawBody = await request.text();

  // -------------------------------------------------------------------------
  // 3. Verify HMAC signature
  //    Use timingSafeEqual to prevent timing-based HMAC forgery attacks.
  // -------------------------------------------------------------------------
  const secret = process.env.SHOPIFY_API_SECRET;
  if (!secret) {
    console.error("SHOPIFY_API_SECRET not configured");
    return new Response("Internal configuration error", { status: 500 });
  }

  const computedDigest = createHmac("sha256", secret)
    .update(rawBody, "utf8")
    .digest("base64");

  let isValid = false;
  try {
    isValid = timingSafeEqual(
      Buffer.from(hmacHeader, "base64"),
      Buffer.from(computedDigest, "base64")
    );
  } catch {
    isValid = false;
  }

  if (!isValid) {
    console.warn(`Webhook HMAC verification failed for topic=${topic} shop=${shopDomain}`);
    return new Response("Unauthorized", { status: 401 });
  }

  // -------------------------------------------------------------------------
  // 4. Resolve merchant_id
  // -------------------------------------------------------------------------
  const merchantResult = await db.query<{ id: number }>(
    "SELECT id FROM merchants WHERE shopify_domain = $1 AND uninstalled_at IS NULL LIMIT 1",
    [shopDomain]
  );

  if (merchantResult.rows.length === 0) {
    // Merchant not found — app/uninstalled webhook may arrive after merchant is removed
    if (topic === "app/uninstalled") {
      return new Response("OK", { status: 200 });
    }
    console.warn(`Webhook received for unknown merchant: ${shopDomain}`);
    return new Response("Merchant not found", { status: 404 });
  }

  const merchantId = merchantResult.rows[0].id;

  // -------------------------------------------------------------------------
  // 5. Handle app/uninstalled inline (lightweight — no background task needed)
  // -------------------------------------------------------------------------
  if (topic === "app/uninstalled") {
    await db.query(
      "UPDATE merchants SET uninstalled_at = NOW(), updated_at = NOW() WHERE id = $1",
      [merchantId]
    );
    return new Response("OK", { status: 200 });
  }

  // -------------------------------------------------------------------------
  // 6. Enqueue background task and return immediately
  // -------------------------------------------------------------------------
  let payload: unknown;
  try {
    payload = JSON.parse(rawBody);
  } catch {
    return new Response("Invalid JSON payload", { status: 400 });
  }

  try {
    await enqueueWebhookTask(topic, merchantId, payload);
  } catch (err) {
    // Log but don't fail — Shopify will retry if we return non-200
    console.error(`Failed to enqueue webhook task for topic=${topic}:`, err);
    return new Response("Failed to enqueue task", { status: 500 });
  }

  return new Response("OK", { status: 200 });
};
